#cloud-config
users:
  - name: srv-01
    sudo: ALL=(ALL) NOPASSWD:ALL
    lock_passwd: false
    passwd: "$6$randomsalt$TP1RQj..." # Пароль в зашифрованном виде
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCIDANLZA0Q9YrictKCUj6R4d+/kf3ZvZFj2ZEBq9HHIMP0xluKCeQv4z7vbvZWFdfJ27c/UKin4+cC6UNMr86ZlFJTSLrmbY7wLWNada9xneBUCaNZE3BFP/c/dv1rygTkJqDmKUySKEIIMy4DrxTOqGZ00CNZ0sYfa7fnMh0Z8k+vVPk70g5HamaSzw0ElfAe3qQ1VxfEn0ZFpRpitmkbEd2bS6xCt7fCl+P5Fs9GVODsTCqe7D9O2KnRJaxRKdkAneQ1cvOsuDO1jryCgrxZRHv1SuqhD+bAD1z8ciJ2fP+JlKnpR0NVmE4Kykrin6eOwnjP2RUkttIoO3sOb0rZRoTdnaQnBuHSmfo2/kZrCWe/NtnEDe6E7fOMbkL/j72QCVWdcnJcRhcvlOwawGWPprrmfc2Z73Qz2ERQJHy1OKDKe+5zrhLE/6SRB1bOvCoNGVSkk/LMmLDwLhiJLdjjNIZ4cyjbFx8Qkrt0P5U1ewXBSQ8omyANQ6q3uVy8OEU= nurlan@WIN-3DJ38HKQ65I
    shell: /bin/bash
chpasswd:
  list: |
    ubuntu:password
  expire: false

package_update: true
package_upgrade: true
packages:
  - curl
  - net-tools
  - htop

write_files:
  - path: /etc/netplan/50-cloud-init.yaml
    permissions: '0644'
    content: |
      network:
        version: 2
        ethernets:
          ens192:
            dhcp4: no
            addresses:
              - 192.168.200.151/24
            gateway4: 192.168.200.1
            nameservers:
              addresses:
                - 8.8.8.8
                - 8.8.4.4

runcmd:
  - echo "Cloud-init is working!" > /tmp/test.txt
  - netplan apply
  - sed -i 's/^#\?PasswordAuthentication .*/PasswordAuthentication yes/' /etc/ssh/sshd_config
  - sed -i 's/^#\?\(PubkeyAuthentication\).*/\1 yes/' /etc/ssh/sshd_config
  - systemctl restart ssh
